# -- CONFIG FILE --

# PAGES
pages:
  - HOME
  - Whiteboard
  - IELTS Preparation
  - Lesson Planner
  - Syllabus Planner
  - TEFL Theory
  - Discover

# MAIN PAGE
main_page: HOME

# TEFL CHAPTERS INFO
chapter_info_map:
  chapter1:
    label: "Chapter 1"
    title: "Role of the Teacher"
    index: 1
  chapter2:
    label: "Chapter 2"
    title: "Student-Centered Classroom"
    index: 2
  chapter3:
    label: "Chapter 3"
    title: "Methods & Approaches"
    index: 3
  chapter4:
    label: "Chapter 4"
    title: "Lesson Planning"
    index: 4
  chapter5:
    label: "Chapter 5"
    title: "Course Design"
    index: 5
  chapter6:
    label: "Chapter 6"
    title: "Lexis"
    index: 6
  chapter7:
    label: "Chapter 7"
    title: "Grammar"
    index: 7
  chapter8:
    label: "Chapter 8"
    title: "Listening & Reading"
    index: 8
  chapter9:
    label: "Chapter 9"
    title: "Speaking & Writing"
    index: 9
  chapter10:
    label: "Chapter 10"
    title: "Visual Aids & Technology"
    index: 10
  chapter11:
    label: "Chapter 11"
    title: "Cultural Sensitivity"
    index: 11
  extra:
    label: "Extra"
    title: "Notes & Extras"
    index: 12


ielts_map:
  reading:
  listening:
  speaking: 
    strategy1:
      label: "Speaking Part 1"
      title: "Three Steps Response"
      index: 1
    strategy2:
      label: "Speaking Part 2"
      title: "The Long Run Preparation"
      index: 2
    strategy3:
      label: "Brainstorm PPF"
      title: "PPF - Present Past Future"
      index: 3
    strategy4:
      label: "Brainstorm 5s"
      title: "Five Senses"
      index: 4
    topic1:
      label: "Practice Topic 1"
      title: "Nature & Environment"
      index: 5
    topic2:
      label: "Practice Topic 2"
      title: "Technology"
      index: 6
    topic3:
      label: "Practice Topic 3"
      title: "Friendship & Relationships"
      index: 7
    topic4:
      label: "Practice Topic 4"
      title: "Travel & Holiday"
      index: 8
    topic5:
      label: "Practice Topic 5"
      title: "Food & Cooking"
      index: 9
    topic6:
      label: "Practice Topic 6"
      title: "Work & Study"
      index: 10
    topic7:
      label: "Practice Topic 7"
      title: "Health & Fitness"
      index: 11
    topic8:
      label: "Practice Topic 8"
      title: "Shopping & Money"
      index: 12
  writing:
    part1:
      label: "Part 1 - Overview"
      title: "5 Steps"
      index: 13
    part1_1:
      label: "Part 1 Type 1"
      title: "Charts"
      index: 14
    part1_2:
      label: "Part 1 Type 2"
      title: "Maps"
      index: 15
    part1_3:
      label: "Part 1 Type 3"
      title: "Multiple Charts/Graphs"
      index: 16
    part1_4:
      label: "Part 1 Type 4"
      title: "Process"
      index: 17
    part2:
      label: "Part 2 - Overview"
      title: "8 Steps"
      index: 18
    part2_1:
      label: "Part 2 Type 1"
      title: "Advantages & Disadvantages Essay"
      index: 19
    part2_2:
      label: "Part 2 Type 2"
      title: "Discuss Views Essay"
      index: 20
    part2_3:
      label: "Part 2 Type 3"
      title: "Two-Part/Double Question Essay"
      index: 21
    part2_4:
      label: "Part 2 Type 4"
      title: "Opinion Essay"
      index: 22
    part2_5:
      label: "Part 2 Type 5"
      title: "Problem & Solution Essay"
      index: 23
  mock:
    

