# -- CONFIG FILE --

# PAGES
pages:
  - HOME
  - Whiteboard
  - IELTS Preparation
  - Lesson Planner
  - Syllabus Planner
  - TEFL Theory
  - Discover

# MAIN PAGE
main_page: HOME

# TEFL CHAPTERS INFO
chapter_info_map:
  chapter1:
    label: "Chapter 1"
    title: "Role of the Teacher"
    index: 1
  chapter2:
    label: "Chapter 2"
    title: "Student-Centered Classroom"
    index: 2
  chapter3:
    label: "Chapter 3"
    title: "Methods & Approaches"
    index: 3
  chapter4:
    label: "Chapter 4"
    title: "Lesson Planning"
    index: 4
  chapter5:
    label: "Chapter 5"
    title: "Course Design"
    index: 5
  chapter6:
    label: "Chapter 6"
    title: "Lexis"
    index: 6
  chapter7:
    label: "Chapter 7"
    title: "Grammar"
    index: 7
  chapter8:
    label: "Chapter 8"
    title: "Listening & Reading"
    index: 8
  chapter9:
    label: "Chapter 9"
    title: "Speaking & Writing"
    index: 9
  chapter10:
    label: "Chapter 10"
    title: "Visual Aids & Technology"
    index: 10
  chapter11:
    label: "Chapter 11"
    title: "Cultural Sensitivity"
    index: 11
  extra:
    label: "Extra"
    title: "Notes & Extras"
    index: 12


ielts_map:
  reading:
  listening:
  speaking: 
    strategy1:
      label: "Speaking Part 1"
      title: "Three Steps Response"
      index: 1
    strategy2:
      label: "Speaking Part 2"
      title: "The Long Run Preparation"
      index: 2
    strategy3:
      label: "Brainstorm PPF"
      title: "PPF - Present Past Future"
      index: 3
    strategy4:
      label: "Brainstorm 5s"
      title: "Five Senses"
      index: 4
    topic1:
      label: "Practice Topic 1"
      title: "Nature & Environment"
      index: 5
    topic2:
      label: "Practice Topic 2"
      title: "Technology"
      index: 6
    topic3:
      label: "Practice Topic 3"
      title: "Friendship & Relationships"
      index: 7
  writing:
    strategy1:
      label: "Part 1"
      title: "Part 1 - Strategy"
      index: 9
    strategy2:
      label: "Part 2"
      title: "Part 2 - Strategy"
      index: 10
    topic1:
      label: "Practice Topic 1"
      title: ""
      index: 11
  mock:
    

